Delete media-fonts/monaco, x11-drivers/nvidia-drivers Fix scripts/e Fix eclasses

diff --git a/scripts/e b/scripts/e
--- a/scripts/e
+++ b/scripts/e
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 # /root/.bin/Gentoo/e - portage management tool
 
+#Test if user is root
+if [ "$(id -u 2>/dev/null)" != "0" ]; then
+  echo "ERROR: $0 must be run as root" >&2
+  exit 1
+fi
+
 package_use="/etc/portage/package.use"
 package_keywords="/etc/portage/package.keywords"
 package_mask="/etc/portage/package.mask"
@@ -117,15 +123,15 @@ case "$1" in
                           layman_base_dir=$(grep ^storage "/etc/layman/layman.cfg"|sed "s/.*:.//")
                         fi
 
-                        if [ -z "${1}" ]; then
+                        if [ -z "${2}" ]; then
                           overlay_dir=$(for file in $(layman -Nl | cut -d" " -f3 | sed "/ *#/d; /^$/d"); do echo "$file" | grep -o --color=never "$1"; done)
                         else
-                          echo "There is no any overlay ${1}"; exit 1
+                          echo "There is no any overlay ${2}"; exit 1
                         fi
 
                         base_dir="${layman_base_dir}/${overlay_dir}"
 
-                        [ -d "${base_dir}" ] && echo "cd ${base_dir}"; cd "${base_dir}" || echo "There is no any ${base_dir}"; exit 1
+                        [ -d "${base_dir}" ] && echo "cd ${base_dir}"; cd "${base_dir}" #|| echo "There is no any ${base_dir}"; exit 1
 
                         echo "Prepare ebuild\`s and ChangeLog"
                         for file in $(find "${base_dir}" \( -name "*.ebuild" -o -name "ChangeLog" \)); do
@@ -144,8 +150,11 @@ case "$1" in
                         find "${base_dir}" -name \*.ebuild -type f -exec ebuild {} digest \; #> /dev/null 2>&1 \;
 
                         echo "Sign all Manifest"
-                        printf "Enter the passphrase for gpg key:\n"
-                        read "PASSPHRASE"
+                        echo -n "Enter the passphrase for gpg key: "
+                        stty -echo
+                        read PASSPHRASE
+                        stty echo
+
                         for file in $(find "${base_dir}" -iname Manifest); do
                           gpg --yes --batch --passphrase="${PASSPHRASE}" --clearsign "${file}";
                           mv "${file}".asc "${file}"
